title: "Oxygen SOP"
logo: images/logo-ocean-gliders.png
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/OceanGlidersCommunity/Oxygen_SOP
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    utterances:
      repo: "OceanGlidersCommunity/Oxygen_SOP"
bibtex_bibfiles:
    - oxygen.bib
sphinx:
  config:
    bibtex_reference_style: author-year
